### ISSUE TITLE
Exclude highlighting on certain domains

### ISSUE THREAD

**Issue by DaleMcGrew** [wevote/WeVoteExtension#10]
Turn off highlighting on these domains:
*.wevote.us
api.wevoteusa.org
localhost

In the future, it would be good to provide the domains to exclude via API, so we can turn highlighting off for client custom domains. (like ballot.motivote.us)

**Comment by SailingSteve** [comment]
This issue was entered on the old repository, before it was renamed to EndorsementExtension

Moved it to https://github.com/wevote/EndorsementExtension/issues/19
